### ISSUE TITLE
pattern not found: global.md

### ISSUE THREAD

**Issue by verajosemanuel** [backdround/global-note.nvim#1]
Great plugin. Exactly what i was searching for. Sadly, i cannot make it work. When pressing leader + n  i get an error `E486: pattern not found: global.md`

I have created the file myself at ~/notes/global.md  but still same error

I am using windows Git bash

**Comment by backdround** [comment]
Could you share your configuration so I can test it myself?

**Comment by backdround** [comment]
Also, does it give you a stacktrace?
Which version of Neovim do you have?

Something could work differently on windows Git bash

**Comment by verajosemanuel** [comment]
Hi, there is no configuration apart from adding a file with the “return” call to your package (I use lazyvim). Neovim version 0.10 dev

**Comment by backdround** [comment]
The plugin doesn't bind any mappings by default. It means that there is something already mapped at `<leader>n`

**Comment by verajosemanuel** [comment]
That error message is clearly from globalnote as it is regarding the global.md file. There is no other mapping for  leader + n

**Comment by backdround** [comment]
The plugin doesn't have any `vim.api.nvim_set_keymap` or `vim.keymap.set` calls, barring the README.md. So it can't bind anything.

The error `E486` relates to search Ex commands like `:global`. The plugin doesn't do such operations. And calls vim commands only once with `vim.cmd.write` which isn't a search command

I assume it's something in the config. Can you provide the configuration and test it again?

**Comment by verajosemanuel** [comment]
here the working config. Running fine now. Thanks for a great plugin!

`return {"backdround/global-note.nvim",
    cmd = "GlobalNote",
    keys = { { "<leader>n", "<cmd>GlobalNote<cr>", desc = "Global Note" } },
    config = true,}`

**Comment by verajosemanuel** [comment]
one question: where is the global.md file located with the working config above?

**Comment by backdround** [comment]
From readme:
```lua
  -- Filename to use for default note (preset).
  -- string or fun(): string
  filename = "global.md",

  -- Directory to keep default note (preset).
  -- string or fun(): string
  directory = vim.fn.stdpath("data") .. "/global-note/",
```
Somewhere there in `vim.fn.stdpath("data")`. The directory is different for different environments

**Comment by verajosemanuel** [comment]
found it. Using Windows the path is: `C:\Users\joe\AppData\Local\nvim-data\global-note`
